CREATE TABLE IF NOT EXISTS translation_request (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	string_to_translate text NOT NULL CHECK (string_to_translate <> ''),
	request_dt timestamp NOT NULL,
	translation_params varchar NOT NULL CHECK (translation_params <> ''),
	ip varchar(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS translation_response (
	translation_request_id BIGINT PRIMARY KEY REFERENCES translation_request (id),
	translated_string text NOT NULL CHECK (translated_string <> '')
);

CREATE TABLE IF NOT EXISTS translation_history (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	translation_request_id BIGINT REFERENCES translation_request (id),
	source_word text NOT NULL CHECK (source_word <> ''),
	translated_word text NOT NULL CHECK (translated_word <> '')
);